version: "3"

services: 
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity